os: linux
dist: xenial
group: stable
language: python
python:
  # Track Python version on future production machines, Debian Stretch.
  - 3.5
  - 3.7
  - 3.8
sudo: required
addons:
  apt:
    packages:
    - g++
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenblas-dev
    - python3-dev
    - enchant
    - aspell-ar
    - aspell-bn
    - aspell-el
    - aspell-id
    - aspell-is
    - aspell-pl
    - aspell-ro
    - aspell-sv
    - aspell-ta
    - aspell-uk
    - myspell-cs
    - myspell-de-at
    - myspell-de-ch
    - myspell-de-de
    - myspell-es
    - myspell-et
    - myspell-fa
    - myspell-fr
    - myspell-he
    - myspell-hr
    - myspell-hu
    - myspell-lv
    - myspell-nb
    - myspell-nl
    - myspell-pt-pt
    - myspell-pt-br
    - myspell-ru
    - myspell-hr
    - hunspell-bs
    - hunspell-ca
    - hunspell-en-au
    - hunspell-en-us
    - hunspell-en-gb
    - hunspell-eu
    - hunspell-gl
    - hunspell-it
    - hunspell-hi
    - hunspell-sr
    - hunspell-vi
    - voikko-fi

before_install: {}
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - python -m nltk.downloader stopwords
  - pip install -r test-requirements.txt
  - pip install twine
script:
  - flake8 . --max-line-length=85 --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,docs
  - pytest --cov=revscoring -m "not nottravis"
  - sphinx-build -anW -b html docs dist/docs
  - sphinx-build -b linkcheck docs dist/docs
after_success:
  - codecov
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  on:
#    branch: master
